name: TheMalteseNetrworkSMP
version: '1.0-SNAPSHOT'
main: dev.memorydealer.ModularPluginSystem
api-version: '1.21'
author: MemoryDealer
commands:
  modules:
    description: Open the Module Management GUI
permissions:
  dev.memorydealer.modules:
    default: op
